-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3n0GSpdy3IbKvIph
jccb9L6H6V6AzwSMDyLLcZDR45egCgYIKoZIzj0DAQehRANCAASuEUhQ8+L5Bp1i
KA1+KZ+twOe/gmVNpkK/RWga/ssAhrLx+/SOwfIyRVQqOm2/69BQsDc/4sTpg4XQ
FbZwRK5h
-----END PRIVATE KEY-----