//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCampus.MobileApp {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("iCampus.MobileApp.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EmptyEmailError {
            get {
                return ResourceManager.GetString("EmptyEmailError", resourceCulture);
            }
        }
        
        internal static string EmptyPasswordError {
            get {
                return ResourceManager.GetString("EmptyPasswordError", resourceCulture);
            }
        }
        
        internal static string BackTitle {
            get {
                return ResourceManager.GetString("BackTitle", resourceCulture);
            }
        }
        
        internal static string HomePageNewsPath {
            get {
                return ResourceManager.GetString("HomePageNewsPath", resourceCulture);
            }
        }
        
        internal static string InternetConnectionError {
            get {
                return ResourceManager.GetString("InternetConnectionError", resourceCulture);
            }
        }
        
        internal static string MobileAppLoginUrlDemo {
            get {
                return ResourceManager.GetString("MobileAppLoginUrlDemo", resourceCulture);
            }
        }
        
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        internal static string SecretKey {
            get {
                return ResourceManager.GetString("SecretKey", resourceCulture);
            }
        }
        
        internal static string MenuStructurePath {
            get {
                return ResourceManager.GetString("MenuStructurePath", resourceCulture);
            }
        }
        
        internal static string StudentPath {
            get {
                return ResourceManager.GetString("StudentPath", resourceCulture);
            }
        }
        
        internal static string InvalidEmailError {
            get {
                return ResourceManager.GetString("InvalidEmailError", resourceCulture);
            }
        }
        
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        internal static string ICampusText {
            get {
                return ResourceManager.GetString("ICampusText", resourceCulture);
            }
        }
        
        internal static string CalendarPageHomeWorkTitle {
            get {
                return ResourceManager.GetString("CalendarPageHomeWorkTitle", resourceCulture);
            }
        }
        
        internal static string CampusKeyPageTitle {
            get {
                return ResourceManager.GetString("CampusKeyPageTitle", resourceCulture);
            }
        }
        
        internal static string CampusKeyApiUrl {
            get {
                return ResourceManager.GetString("CampusKeyApiUrl", resourceCulture);
            }
        }
        
        internal static string CalendarAgendaApiUrl {
            get {
                return ResourceManager.GetString("CalendarAgendaApiUrl", resourceCulture);
            }
        }
        
        internal static string HomeWorkBackTitle {
            get {
                return ResourceManager.GetString("HomeWorkBackTitle", resourceCulture);
            }
        }
        
        internal static string UserDataCache {
            get {
                return ResourceManager.GetString("UserDataCache", resourceCulture);
            }
        }
        
        internal static string BusTrackingPageTitle {
            get {
                return ResourceManager.GetString("BusTrackingPageTitle", resourceCulture);
            }
        }
        
        internal static string CalendarPageTitle {
            get {
                return ResourceManager.GetString("CalendarPageTitle", resourceCulture);
            }
        }
        
        internal static string FilterAgendaTitle {
            get {
                return ResourceManager.GetString("FilterAgendaTitle", resourceCulture);
            }
        }
        
        internal static string AgendaTypePath {
            get {
                return ResourceManager.GetString("AgendaTypePath", resourceCulture);
            }
        }
        
        internal static string CampusKeyInvoiceDetailsApiUrl {
            get {
                return ResourceManager.GetString("CampusKeyInvoiceDetailsApiUrl", resourceCulture);
            }
        }
        
        internal static string ComplaintsPageTitle {
            get {
                return ResourceManager.GetString("ComplaintsPageTitle", resourceCulture);
            }
        }
        
        internal static string ComplaintsListApiUrl {
            get {
                return ResourceManager.GetString("ComplaintsListApiUrl", resourceCulture);
            }
        }
        
        internal static string NextIcon {
            get {
                return ResourceManager.GetString("NextIcon", resourceCulture);
            }
        }
        
        internal static string CampusKeyDetailsAED {
            get {
                return ResourceManager.GetString("CampusKeyDetailsAED", resourceCulture);
            }
        }
        
        internal static string CampusKeyDetailsBilNo {
            get {
                return ResourceManager.GetString("CampusKeyDetailsBilNo", resourceCulture);
            }
        }
        
        internal static string CampusKeyDetailsTotal {
            get {
                return ResourceManager.GetString("CampusKeyDetailsTotal", resourceCulture);
            }
        }
        
        internal static string EventCommandErrorText {
            get {
                return ResourceManager.GetString("EventCommandErrorText", resourceCulture);
            }
        }
        
        internal static string NewsPageTitle {
            get {
                return ResourceManager.GetString("NewsPageTitle", resourceCulture);
            }
        }
        
        internal static string BusTrackingApiUrl {
            get {
                return ResourceManager.GetString("BusTrackingApiUrl", resourceCulture);
            }
        }
        
        internal static string CommunicationPageTitle {
            get {
                return ResourceManager.GetString("CommunicationPageTitle", resourceCulture);
            }
        }
        
        internal static string DownArrowText {
            get {
                return ResourceManager.GetString("DownArrowText", resourceCulture);
            }
        }
        
        internal static string InboxText {
            get {
                return ResourceManager.GetString("InboxText", resourceCulture);
            }
        }
        
        internal static string SentText {
            get {
                return ResourceManager.GetString("SentText", resourceCulture);
            }
        }
        
        internal static string TimeTablePageTitle {
            get {
                return ResourceManager.GetString("TimeTablePageTitle", resourceCulture);
            }
        }
        
        internal static string TimeTableApiUrl {
            get {
                return ResourceManager.GetString("TimeTableApiUrl", resourceCulture);
            }
        }
        
        internal static string ExamApiUrl {
            get {
                return ResourceManager.GetString("ExamApiUrl", resourceCulture);
            }
        }
        
        internal static string TimeTableFilePathErrorMessage {
            get {
                return ResourceManager.GetString("TimeTableFilePathErrorMessage", resourceCulture);
            }
        }
        
        internal static string BusAttendanceDetailsAPIUrl {
            get {
                return ResourceManager.GetString("BusAttendanceDetailsAPIUrl", resourceCulture);
            }
        }
        
        internal static string BusAttendanceHeaderTitle {
            get {
                return ResourceManager.GetString("BusAttendanceHeaderTitle", resourceCulture);
            }
        }
        
        internal static string FromSchool {
            get {
                return ResourceManager.GetString("FromSchool", resourceCulture);
            }
        }
        
        internal static string ToSchool {
            get {
                return ResourceManager.GetString("ToSchool", resourceCulture);
            }
        }
        
        internal static string DateFormatKey {
            get {
                return ResourceManager.GetString("DateFormatKey", resourceCulture);
            }
        }
        
        internal static string PastExamText {
            get {
                return ResourceManager.GetString("PastExamText", resourceCulture);
            }
        }
        
        internal static string UpcomingExamText {
            get {
                return ResourceManager.GetString("UpcomingExamText", resourceCulture);
            }
        }
        
        internal static string NextText {
            get {
                return ResourceManager.GetString("NextText", resourceCulture);
            }
        }
        
        internal static string PreviousText {
            get {
                return ResourceManager.GetString("PreviousText", resourceCulture);
            }
        }
        
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        internal static string ReportCardApiUrl {
            get {
                return ResourceManager.GetString("ReportCardApiUrl", resourceCulture);
            }
        }
        
        internal static string ReportCardText {
            get {
                return ResourceManager.GetString("ReportCardText", resourceCulture);
            }
        }
        
        internal static string CircularListApiUrl {
            get {
                return ResourceManager.GetString("CircularListApiUrl", resourceCulture);
            }
        }
        
        internal static string MessageFromSchoolPageTitle {
            get {
                return ResourceManager.GetString("MessageFromSchoolPageTitle", resourceCulture);
            }
        }
        
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        internal static string ReportIssueAlertMsg {
            get {
                return ResourceManager.GetString("ReportIssueAlertMsg", resourceCulture);
            }
        }
        
        internal static string ReportIssueAlertTitle {
            get {
                return ResourceManager.GetString("ReportIssueAlertTitle", resourceCulture);
            }
        }
        
        internal static string AboutUrl {
            get {
                return ResourceManager.GetString("AboutUrl", resourceCulture);
            }
        }
        
        internal static string HelpCenterUrl {
            get {
                return ResourceManager.GetString("HelpCenterUrl", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        internal static string CommunicationApiUrl {
            get {
                return ResourceManager.GetString("CommunicationApiUrl", resourceCulture);
            }
        }
        
        internal static string CommunicationDateFormatKey {
            get {
                return ResourceManager.GetString("CommunicationDateFormatKey", resourceCulture);
            }
        }
        
        internal static string ActiveTermApiUrl {
            get {
                return ResourceManager.GetString("ActiveTermApiUrl", resourceCulture);
            }
        }
        
        internal static string FilterReportCardTitle {
            get {
                return ResourceManager.GetString("FilterReportCardTitle", resourceCulture);
            }
        }
        
        internal static string EventPageApiUrl {
            get {
                return ResourceManager.GetString("EventPageApiUrl", resourceCulture);
            }
        }
        
        internal static string EventPageTitle {
            get {
                return ResourceManager.GetString("EventPageTitle", resourceCulture);
            }
        }
        
        internal static string FilterEventTitle {
            get {
                return ResourceManager.GetString("FilterEventTitle", resourceCulture);
            }
        }
        
        internal static string AlertsPageTitle {
            get {
                return ResourceManager.GetString("AlertsPageTitle", resourceCulture);
            }
        }
        
        internal static string CircularsPageTitle {
            get {
                return ResourceManager.GetString("CircularsPageTitle", resourceCulture);
            }
        }
        
        internal static string LogoutApiUrl {
            get {
                return ResourceManager.GetString("LogoutApiUrl", resourceCulture);
            }
        }
        
        internal static string FinancialStatementApiUrl {
            get {
                return ResourceManager.GetString("FinancialStatementApiUrl", resourceCulture);
            }
        }
        
        internal static string ClearCacheAlertMsg {
            get {
                return ResourceManager.GetString("ClearCacheAlertMsg", resourceCulture);
            }
        }
        
        internal static string ClearCacheText {
            get {
                return ResourceManager.GetString("ClearCacheText", resourceCulture);
            }
        }
        
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        internal static string PushNotificationKey {
            get {
                return ResourceManager.GetString("PushNotificationKey", resourceCulture);
            }
        }
        
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
        
        internal static string CommunicationDetailsAPIUrl {
            get {
                return ResourceManager.GetString("CommunicationDetailsAPIUrl", resourceCulture);
            }
        }
        
        internal static string FinancialStatementText {
            get {
                return ResourceManager.GetString("FinancialStatementText", resourceCulture);
            }
        }
        
        internal static string DeleteConfirmationMessageText {
            get {
                return ResourceManager.GetString("DeleteConfirmationMessageText", resourceCulture);
            }
        }
        
        internal static string DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        internal static string DeleteMessageAPIUrl {
            get {
                return ResourceManager.GetString("DeleteMessageAPIUrl", resourceCulture);
            }
        }
        
        internal static string SchoolContactDetailsApiUrl {
            get {
                return ResourceManager.GetString("SchoolContactDetailsApiUrl", resourceCulture);
            }
        }
        
        internal static string ContactUsPageTitle {
            get {
                return ResourceManager.GetString("ContactUsPageTitle", resourceCulture);
            }
        }
        
        internal static string AttendanceApiUrl {
            get {
                return ResourceManager.GetString("AttendanceApiUrl", resourceCulture);
            }
        }
        
        internal static string BeamAttendanceApiUrl {
            get {
                return ResourceManager.GetString("BeamAttendanceApiUrl", resourceCulture);
            }
        }
        
        internal static string FilterAttendanceTitle {
            get {
                return ResourceManager.GetString("FilterAttendanceTitle", resourceCulture);
            }
        }
        
        internal static string SendMessagePageTitle {
            get {
                return ResourceManager.GetString("SendMessagePageTitle", resourceCulture);
            }
        }
        
        internal static string TroubleSignInInformation {
            get {
                return ResourceManager.GetString("TroubleSignInInformation", resourceCulture);
            }
        }
        
        internal static string TroubleSignInTitle {
            get {
                return ResourceManager.GetString("TroubleSignInTitle", resourceCulture);
            }
        }
        
        internal static string TeacherAppointmentApiUrl {
            get {
                return ResourceManager.GetString("TeacherAppointmentApiUrl", resourceCulture);
            }
        }
        
        internal static string TeacherAppointmentTitle {
            get {
                return ResourceManager.GetString("TeacherAppointmentTitle", resourceCulture);
            }
        }
        
        internal static string AttendanceTermApiUrlPath {
            get {
                return ResourceManager.GetString("AttendanceTermApiUrlPath", resourceCulture);
            }
        }
        
        internal static string DateFormatKey1 {
            get {
                return ResourceManager.GetString("DateFormatKey1", resourceCulture);
            }
        }
        
        internal static string DateFormatKey2 {
            get {
                return ResourceManager.GetString("DateFormatKey2", resourceCulture);
            }
        }
        
        internal static string DateFormatKey3 {
            get {
                return ResourceManager.GetString("DateFormatKey3", resourceCulture);
            }
        }
        
        internal static string StudentConductDataApiUrl {
            get {
                return ResourceManager.GetString("StudentConductDataApiUrl", resourceCulture);
            }
        }
        
        internal static string RecipientListApiUrl {
            get {
                return ResourceManager.GetString("RecipientListApiUrl", resourceCulture);
            }
        }
        
        internal static string SendMessageApiUrl {
            get {
                return ResourceManager.GetString("SendMessageApiUrl", resourceCulture);
            }
        }
        
        internal static string RaiseComplaintsTitle {
            get {
                return ResourceManager.GetString("RaiseComplaintsTitle", resourceCulture);
            }
        }
        
        internal static string RecipientSelectionInfoMessage {
            get {
                return ResourceManager.GetString("RecipientSelectionInfoMessage", resourceCulture);
            }
        }
        
        internal static string RecipientSelectionInfoText {
            get {
                return ResourceManager.GetString("RecipientSelectionInfoText", resourceCulture);
            }
        }
        
        internal static string ContactUsMessageTemplate {
            get {
                return ResourceManager.GetString("ContactUsMessageTemplate", resourceCulture);
            }
        }
        
        internal static string ContactUsSendMessageApiUrl {
            get {
                return ResourceManager.GetString("ContactUsSendMessageApiUrl", resourceCulture);
            }
        }
        
        internal static string FilterConductTitle {
            get {
                return ResourceManager.GetString("FilterConductTitle", resourceCulture);
            }
        }
        
        internal static string FilterMedicalTitle {
            get {
                return ResourceManager.GetString("FilterMedicalTitle", resourceCulture);
            }
        }
        
        internal static string SendComplaintApiUrl {
            get {
                return ResourceManager.GetString("SendComplaintApiUrl", resourceCulture);
            }
        }
        
        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        internal static string EditComplaintTitle {
            get {
                return ResourceManager.GetString("EditComplaintTitle", resourceCulture);
            }
        }
        
        internal static string CustomAlertsApiUrl {
            get {
                return ResourceManager.GetString("CustomAlertsApiUrl", resourceCulture);
            }
        }
        
        internal static string DeleteComplaintApiUrl {
            get {
                return ResourceManager.GetString("DeleteComplaintApiUrl", resourceCulture);
            }
        }
        
        internal static string ContactUsEmailSubject {
            get {
                return ResourceManager.GetString("ContactUsEmailSubject", resourceCulture);
            }
        }
        
        internal static string EmptyContactError {
            get {
                return ResourceManager.GetString("EmptyContactError", resourceCulture);
            }
        }
        
        internal static string EmptyMessageError {
            get {
                return ResourceManager.GetString("EmptyMessageError", resourceCulture);
            }
        }
        
        internal static string EmptyNameError {
            get {
                return ResourceManager.GetString("EmptyNameError", resourceCulture);
            }
        }
        
        internal static string EmptyTypeError {
            get {
                return ResourceManager.GetString("EmptyTypeError", resourceCulture);
            }
        }
        
        internal static string AttendanceDetailsApiUrl {
            get {
                return ResourceManager.GetString("AttendanceDetailsApiUrl", resourceCulture);
            }
        }
        
        internal static string CommunicationReplyApiUrl {
            get {
                return ResourceManager.GetString("CommunicationReplyApiUrl", resourceCulture);
            }
        }
        
        internal static string UpdateCustomAlertApiUrl {
            get {
                return ResourceManager.GetString("UpdateCustomAlertApiUrl", resourceCulture);
            }
        }
        
        internal static string TodaysDateTimeFormatKey {
            get {
                return ResourceManager.GetString("TodaysDateTimeFormatKey", resourceCulture);
            }
        }
        
        internal static string PleaseEnterComment {
            get {
                return ResourceManager.GetString("PleaseEnterComment", resourceCulture);
            }
        }
        
        internal static string TeacherAppointmentDeleteApiUrl {
            get {
                return ResourceManager.GetString("TeacherAppointmentDeleteApiUrl", resourceCulture);
            }
        }
        
        internal static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        internal static string FamilyAppointmentUrl {
            get {
                return ResourceManager.GetString("FamilyAppointmentUrl", resourceCulture);
            }
        }
        
        internal static string FamilyAppointmentPageTitle {
            get {
                return ResourceManager.GetString("FamilyAppointmentPageTitle", resourceCulture);
            }
        }
        
        internal static string AppointmentComments {
            get {
                return ResourceManager.GetString("AppointmentComments", resourceCulture);
            }
        }
        
        internal static string LogoutPopupConfirmationText {
            get {
                return ResourceManager.GetString("LogoutPopupConfirmationText", resourceCulture);
            }
        }
        
        internal static string LogoutPopupTitle {
            get {
                return ResourceManager.GetString("LogoutPopupTitle", resourceCulture);
            }
        }
        
        internal static string EmptyMessageBodyError {
            get {
                return ResourceManager.GetString("EmptyMessageBodyError", resourceCulture);
            }
        }
        
        internal static string EmptyMessageSubjectErrror {
            get {
                return ResourceManager.GetString("EmptyMessageSubjectErrror", resourceCulture);
            }
        }
        
        internal static string EmptyRecipientError {
            get {
                return ResourceManager.GetString("EmptyRecipientError", resourceCulture);
            }
        }
        
        internal static string EmptyFromError {
            get {
                return ResourceManager.GetString("EmptyFromError", resourceCulture);
            }
        }
        
        internal static string UpdateTeacherAppointmentApiUrl {
            get {
                return ResourceManager.GetString("UpdateTeacherAppointmentApiUrl", resourceCulture);
            }
        }
        
        internal static string AppointmentAvailableTimeApiUrl {
            get {
                return ResourceManager.GetString("AppointmentAvailableTimeApiUrl", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string UpdateFamilyAppointmentCommentUrl {
            get {
                return ResourceManager.GetString("UpdateFamilyAppointmentCommentUrl", resourceCulture);
            }
        }
        
        internal static string EmailSendingFailed {
            get {
                return ResourceManager.GetString("EmailSendingFailed", resourceCulture);
            }
        }
        
        internal static string DefaultButtonColor {
            get {
                return ResourceManager.GetString("DefaultButtonColor", resourceCulture);
            }
        }
        
        internal static string UpdateFamilyAppointmentStatusUrl {
            get {
                return ResourceManager.GetString("UpdateFamilyAppointmentStatusUrl", resourceCulture);
            }
        }
        
        internal static string AppointmentConfirmationMessage {
            get {
                return ResourceManager.GetString("AppointmentConfirmationMessage", resourceCulture);
            }
        }
        
        internal static string BookTeacherAppointmentApiUrl {
            get {
                return ResourceManager.GetString("BookTeacherAppointmentApiUrl", resourceCulture);
            }
        }
        
        internal static string AppointmentUpdatedSuccess {
            get {
                return ResourceManager.GetString("AppointmentUpdatedSuccess", resourceCulture);
            }
        }
        
        internal static string PushNotificationDisabledMessage {
            get {
                return ResourceManager.GetString("PushNotificationDisabledMessage", resourceCulture);
            }
        }
        
        internal static string PushNotificationIntervalMinutes {
            get {
                return ResourceManager.GetString("PushNotificationIntervalMinutes", resourceCulture);
            }
        }
        
        internal static string PushNotificationListApiUrl {
            get {
                return ResourceManager.GetString("PushNotificationListApiUrl", resourceCulture);
            }
        }
        
        internal static string FileTypeNotAllowed {
            get {
                return ResourceManager.GetString("FileTypeNotAllowed", resourceCulture);
            }
        }
        
        internal static string LargeFileSize {
            get {
                return ResourceManager.GetString("LargeFileSize", resourceCulture);
            }
        }
        
        internal static string PushNotificationTitle {
            get {
                return ResourceManager.GetString("PushNotificationTitle", resourceCulture);
            }
        }
        
        internal static string DeviceMaxPortraitSize {
            get {
                return ResourceManager.GetString("DeviceMaxPortraitSize", resourceCulture);
            }
        }
        
        internal static string SenderValueMaxLength {
            get {
                return ResourceManager.GetString("SenderValueMaxLength", resourceCulture);
            }
        }
        
        internal static string NoNewPushNotificationsMessage {
            get {
                return ResourceManager.GetString("NoNewPushNotificationsMessage", resourceCulture);
            }
        }
        
        internal static string EmptyPushNotificationsIcon {
            get {
                return ResourceManager.GetString("EmptyPushNotificationsIcon", resourceCulture);
            }
        }
        
        internal static string FilledPushNotificationsIcon {
            get {
                return ResourceManager.GetString("FilledPushNotificationsIcon", resourceCulture);
            }
        }
        
        internal static string PushNotificationsCountKey {
            get {
                return ResourceManager.GetString("PushNotificationsCountKey", resourceCulture);
            }
        }
        
        internal static string SearchStudentAttendanceTitle {
            get {
                return ResourceManager.GetString("SearchStudentAttendanceTitle", resourceCulture);
            }
        }
        
        internal static string SISApiConfigurationUrl {
            get {
                return ResourceManager.GetString("SISApiConfigurationUrl", resourceCulture);
            }
        }
        
        internal static string StudentAttendanceApiUrl {
            get {
                return ResourceManager.GetString("StudentAttendanceApiUrl", resourceCulture);
            }
        }
        
        internal static string GetStudentCourseAndClassApiUrl {
            get {
                return ResourceManager.GetString("GetStudentCourseAndClassApiUrl", resourceCulture);
            }
        }
        
        internal static string GetStudentPeriodApiUrl {
            get {
                return ResourceManager.GetString("GetStudentPeriodApiUrl", resourceCulture);
            }
        }
        
        internal static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        internal static string StudentAttendanceFilterListApiUrl {
            get {
                return ResourceManager.GetString("StudentAttendanceFilterListApiUrl", resourceCulture);
            }
        }
        
        internal static string UpdateAttendanceApiUrl {
            get {
                return ResourceManager.GetString("UpdateAttendanceApiUrl", resourceCulture);
            }
        }
        
        internal static string StudentAttendancePageTitle {
            get {
                return ResourceManager.GetString("StudentAttendancePageTitle", resourceCulture);
            }
        }
        
        internal static string AttendanceSaveSuccessMessage {
            get {
                return ResourceManager.GetString("AttendanceSaveSuccessMessage", resourceCulture);
            }
        }
        
        internal static string GetTeacherRelativeClassesByCourse {
            get {
                return ResourceManager.GetString("GetTeacherRelativeClassesByCourse", resourceCulture);
            }
        }
        
        internal static string ExamPageTitle {
            get {
                return ResourceManager.GetString("ExamPageTitle", resourceCulture);
            }
        }
        
        internal static string TeacherAppointmentPageTitle {
            get {
                return ResourceManager.GetString("TeacherAppointmentPageTitle", resourceCulture);
            }
        }
        
        internal static string MinimumCacheRecordSize {
            get {
                return ResourceManager.GetString("MinimumCacheRecordSize", resourceCulture);
            }
        }
        
        internal static string DataRefreshTimerIntervalMinutes {
            get {
                return ResourceManager.GetString("DataRefreshTimerIntervalMinutes", resourceCulture);
            }
        }
        
        internal static string HomePageDataApiUrl {
            get {
                return ResourceManager.GetString("HomePageDataApiUrl", resourceCulture);
            }
        }
        
        internal static string UserAppInfoUpdateApiUrl {
            get {
                return ResourceManager.GetString("UserAppInfoUpdateApiUrl", resourceCulture);
            }
        }
        
        internal static string UpdateAppMessage {
            get {
                return ResourceManager.GetString("UpdateAppMessage", resourceCulture);
            }
        }
        
        internal static string UpdateAppTitle {
            get {
                return ResourceManager.GetString("UpdateAppTitle", resourceCulture);
            }
        }
        
        internal static string UpdateLaterText {
            get {
                return ResourceManager.GetString("UpdateLaterText", resourceCulture);
            }
        }
        
        internal static string UpdateNowText {
            get {
                return ResourceManager.GetString("UpdateNowText", resourceCulture);
            }
        }
        
        internal static string UpdateNotificationSettingApiUrl {
            get {
                return ResourceManager.GetString("UpdateNotificationSettingApiUrl", resourceCulture);
            }
        }
        
        internal static string UpdateTokenApiUrl {
            get {
                return ResourceManager.GetString("UpdateTokenApiUrl", resourceCulture);
            }
        }
        
        internal static string AgendaCancellationText {
            get {
                return ResourceManager.GetString("AgendaCancellationText", resourceCulture);
            }
        }
        
        internal static string SearchDailyMarks {
            get {
                return ResourceManager.GetString("SearchDailyMarks", resourceCulture);
            }
        }
        
        internal static string DailyMarksApiUrl {
            get {
                return ResourceManager.GetString("DailyMarksApiUrl", resourceCulture);
            }
        }
        
        internal static string NoAppointmentDateMessage {
            get {
                return ResourceManager.GetString("NoAppointmentDateMessage", resourceCulture);
            }
        }
        
        internal static string CommunicationClassListApiUrl {
            get {
                return ResourceManager.GetString("CommunicationClassListApiUrl", resourceCulture);
            }
        }
        
        internal static string CommunicationGradeListApiUrl {
            get {
                return ResourceManager.GetString("CommunicationGradeListApiUrl", resourceCulture);
            }
        }
        
        internal static string IsDemoApp {
            get {
                return ResourceManager.GetString("IsDemoApp", resourceCulture);
            }
        }
        
        internal static string MobileAppLoginUrlLive {
            get {
                return ResourceManager.GetString("MobileAppLoginUrlLive", resourceCulture);
            }
        }
        
        internal static string BeamMobileAppLoginUrlLive {
            get {
                return ResourceManager.GetString("BeamMobileAppLoginUrlLive", resourceCulture);
            }
        }
        
        internal static string FamilyAppointmentStatusUpdateApiUrl {
            get {
                return ResourceManager.GetString("FamilyAppointmentStatusUpdateApiUrl", resourceCulture);
            }
        }
        
        internal static string AppointmentApproveMessage {
            get {
                return ResourceManager.GetString("AppointmentApproveMessage", resourceCulture);
            }
        }
        
        internal static string AppointmentCompleteMessage {
            get {
                return ResourceManager.GetString("AppointmentCompleteMessage", resourceCulture);
            }
        }
        
        internal static string ApproveConfirmationMessage {
            get {
                return ResourceManager.GetString("ApproveConfirmationMessage", resourceCulture);
            }
        }
        
        internal static string CompleteConfirmationMessage {
            get {
                return ResourceManager.GetString("CompleteConfirmationMessage", resourceCulture);
            }
        }
        
        internal static string SendingFailedMessage {
            get {
                return ResourceManager.GetString("SendingFailedMessage", resourceCulture);
            }
        }
        
        internal static string LocationAccessDeniedMessage {
            get {
                return ResourceManager.GetString("LocationAccessDeniedMessage", resourceCulture);
            }
        }
        
        internal static string LocationAccessDeniedTitle {
            get {
                return ResourceManager.GetString("LocationAccessDeniedTitle", resourceCulture);
            }
        }
        
        internal static string NextWeekText {
            get {
                return ResourceManager.GetString("NextWeekText", resourceCulture);
            }
        }
        
        internal static string PrevWeekText {
            get {
                return ResourceManager.GetString("PrevWeekText", resourceCulture);
            }
        }
        
        internal static string ThisWeekText {
            get {
                return ResourceManager.GetString("ThisWeekText", resourceCulture);
            }
        }
        
        internal static string WeekDateFormatKey {
            get {
                return ResourceManager.GetString("WeekDateFormatKey", resourceCulture);
            }
        }
        
        internal static string GetAgendaColorApiUrl {
            get {
                return ResourceManager.GetString("GetAgendaColorApiUrl", resourceCulture);
            }
        }
        
        internal static string AutoLogoutMessage {
            get {
                return ResourceManager.GetString("AutoLogoutMessage", resourceCulture);
            }
        }
        
        internal static string AutoLogoutTitle {
            get {
                return ResourceManager.GetString("AutoLogoutTitle", resourceCulture);
            }
        }
        
        internal static string SkillReportCardText {
            get {
                return ResourceManager.GetString("SkillReportCardText", resourceCulture);
            }
        }
        
        internal static string SelectRecipientText {
            get {
                return ResourceManager.GetString("SelectRecipientText", resourceCulture);
            }
        }
        
        internal static string BeamSelectRecipientText {
            get {
                return ResourceManager.GetString("BeamSelectRecipientText", resourceCulture);
            }
        }
        
        internal static string RecipientDataCacheTime {
            get {
                return ResourceManager.GetString("RecipientDataCacheTime", resourceCulture);
            }
        }
        
        internal static string RecipientRestrictionAlertMessage {
            get {
                return ResourceManager.GetString("RecipientRestrictionAlertMessage", resourceCulture);
            }
        }
        
        internal static string SurveyDetailsApiUrl {
            get {
                return ResourceManager.GetString("SurveyDetailsApiUrl", resourceCulture);
            }
        }
        
        internal static string SurveyValidationMsg {
            get {
                return ResourceManager.GetString("SurveyValidationMsg", resourceCulture);
            }
        }
        
        internal static string SurveySubmitApiUrl {
            get {
                return ResourceManager.GetString("SurveySubmitApiUrl", resourceCulture);
            }
        }
        
        internal static string SurveySubmitMsg {
            get {
                return ResourceManager.GetString("SurveySubmitMsg", resourceCulture);
            }
        }
        
        internal static string SurveyPageTitle {
            get {
                return ResourceManager.GetString("SurveyPageTitle", resourceCulture);
            }
        }
        
        internal static string GetPendingSurveysApiUrl {
            get {
                return ResourceManager.GetString("GetPendingSurveysApiUrl", resourceCulture);
            }
        }
        
        internal static string GetPendingDataCollectionApiUrl {
            get {
                return ResourceManager.GetString("GetPendingDataCollectionApiUrl", resourceCulture);
            }
        }
        
        internal static string SaveDataCollectionApiUrl {
            get {
                return ResourceManager.GetString("SaveDataCollectionApiUrl", resourceCulture);
            }
        }
        
        internal static string DataCollectionPageTitle {
            get {
                return ResourceManager.GetString("DataCollectionPageTitle", resourceCulture);
            }
        }
        
        internal static string DataCollectionSubmitMsg {
            get {
                return ResourceManager.GetString("DataCollectionSubmitMsg", resourceCulture);
            }
        }
        
        internal static string PhoneValidationMsg {
            get {
                return ResourceManager.GetString("PhoneValidationMsg", resourceCulture);
            }
        }
        
        internal static string EmailValidationMsg {
            get {
                return ResourceManager.GetString("EmailValidationMsg", resourceCulture);
            }
        }
        
        internal static string GetAllDataCollectionApiUrl {
            get {
                return ResourceManager.GetString("GetAllDataCollectionApiUrl", resourceCulture);
            }
        }
        
        internal static string GetDataCollectionApiUrl {
            get {
                return ResourceManager.GetString("GetDataCollectionApiUrl", resourceCulture);
            }
        }
        
        internal static string TroubleSignInEmailCS {
            get {
                return ResourceManager.GetString("TroubleSignInEmailCS", resourceCulture);
            }
        }
        
        internal static string TroubleSignInEmailCAS {
            get {
                return ResourceManager.GetString("TroubleSignInEmailCAS", resourceCulture);
            }
        }
        
        internal static string TroubleSignInGeneralEmail {
            get {
                return ResourceManager.GetString("TroubleSignInGeneralEmail", resourceCulture);
            }
        }
        
        internal static string OnlinePaymentDetails {
            get {
                return ResourceManager.GetString("OnlinePaymentDetails", resourceCulture);
            }
        }
        
        internal static string GetTaxReceiptDetails {
            get {
                return ResourceManager.GetString("GetTaxReceiptDetails", resourceCulture);
            }
        }
        
        internal static string InvalidOtherAmountErrorMessage {
            get {
                return ResourceManager.GetString("InvalidOtherAmountErrorMessage", resourceCulture);
            }
        }
        
        internal static string OtherAmountEmptyErrorMessage {
            get {
                return ResourceManager.GetString("OtherAmountEmptyErrorMessage", resourceCulture);
            }
        }
        
        internal static string MandatoryFieldErrorMessage {
            get {
                return ResourceManager.GetString("MandatoryFieldErrorMessage", resourceCulture);
            }
        }
        
        internal static string GetBillingDetails {
            get {
                return ResourceManager.GetString("GetBillingDetails", resourceCulture);
            }
        }
        
        internal static string InitiateNGeniusPAyment {
            get {
                return ResourceManager.GetString("InitiateNGeniusPAyment", resourceCulture);
            }
        }
        
        internal static string GetTaxReceiptDetailsAfterSuccessfulPayment {
            get {
                return ResourceManager.GetString("GetTaxReceiptDetailsAfterSuccessfulPayment", resourceCulture);
            }
        }
        
        internal static string UpdateTransactionFailed {
            get {
                return ResourceManager.GetString("UpdateTransactionFailed", resourceCulture);
            }
        }
        
        internal static string UpdatePaymentCancelled {
            get {
                return ResourceManager.GetString("UpdatePaymentCancelled", resourceCulture);
            }
        }
        
        internal static string UpdateSuccessfulPayment {
            get {
                return ResourceManager.GetString("UpdateSuccessfulPayment", resourceCulture);
            }
        }
        
        internal static string BeamTroubleSignInInformation {
            get {
                return ResourceManager.GetString("BeamTroubleSignInInformation", resourceCulture);
            }
        }
        
        internal static string BeamReportIssueAlertMsg {
            get {
                return ResourceManager.GetString("BeamReportIssueAlertMsg", resourceCulture);
            }
        }
        
        internal static string DeleteCovidTestDetailsConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteCovidTestDetailsConfirmationMessage", resourceCulture);
            }
        }
        
        internal static string GetCovidTestData {
            get {
                return ResourceManager.GetString("GetCovidTestData", resourceCulture);
            }
        }
        
        internal static string UpdateCovidTestData {
            get {
                return ResourceManager.GetString("UpdateCovidTestData", resourceCulture);
            }
        }
        
        internal static string DeleteCovidTestData {
            get {
                return ResourceManager.GetString("DeleteCovidTestData", resourceCulture);
            }
        }
        
        internal static string GetStudentMedicalIncidents {
            get {
                return ResourceManager.GetString("GetStudentMedicalIncidents", resourceCulture);
            }
        }
        
        internal static string GetStudentMedicalVaccinationDetails {
            get {
                return ResourceManager.GetString("GetStudentMedicalVaccinationDetails", resourceCulture);
            }
        }
        
        internal static string AgendasDueText {
            get {
                return ResourceManager.GetString("AgendasDueText", resourceCulture);
            }
        }
        
        internal static string AssignmentDashboardDataAPIUrl {
            get {
                return ResourceManager.GetString("AssignmentDashboardDataAPIUrl", resourceCulture);
            }
        }
        
        internal static string NotificationCenterAPIUrl {
            get {
                return ResourceManager.GetString("NotificationCenterAPIUrl", resourceCulture);
            }
        }
        
        internal static string ResourcesDataAPIUrl {
            get {
                return ResourceManager.GetString("ResourcesDataAPIUrl", resourceCulture);
            }
        }
        
        internal static string ResourceDetailsApiUrl {
            get {
                return ResourceManager.GetString("ResourceDetailsApiUrl", resourceCulture);
            }
        }
        
        internal static string GetTeacherClassesByGradeApiUrl {
            get {
                return ResourceManager.GetString("GetTeacherClassesByGradeApiUrl", resourceCulture);
            }
        }
        
        internal static string DeleteResourceApiUrl {
            get {
                return ResourceManager.GetString("DeleteResourceApiUrl", resourceCulture);
            }
        }
        
        internal static string UpdateResourceDataApiUrl {
            get {
                return ResourceManager.GetString("UpdateResourceDataApiUrl", resourceCulture);
            }
        }
        
        internal static string FilterResourcesTitle {
            get {
                return ResourceManager.GetString("FilterResourcesTitle", resourceCulture);
            }
        }
        
        internal static string GetBooksReservationDataApiUrl {
            get {
                return ResourceManager.GetString("GetBooksReservationDataApiUrl", resourceCulture);
            }
        }
        
        internal static string MandatoryBookSelectionAlert {
            get {
                return ResourceManager.GetString("MandatoryBookSelectionAlert", resourceCulture);
            }
        }
        
        internal static string SkipStudentForBookReservationApiUrl {
            get {
                return ResourceManager.GetString("SkipStudentForBookReservationApiUrl", resourceCulture);
            }
        }
        
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        internal static string SelectBooksCollectionDateConfirmationMessage {
            get {
                return ResourceManager.GetString("SelectBooksCollectionDateConfirmationMessage", resourceCulture);
            }
        }
        
        internal static string GetAppointmentAvailableTimes {
            get {
                return ResourceManager.GetString("GetAppointmentAvailableTimes", resourceCulture);
            }
        }
        
        internal static string SelectCollectionDateText {
            get {
                return ResourceManager.GetString("SelectCollectionDateText", resourceCulture);
            }
        }
        
        internal static string BooksReservationApiUrl {
            get {
                return ResourceManager.GetString("BooksReservationApiUrl", resourceCulture);
            }
        }
        
        internal static string NewPostText {
            get {
                return ResourceManager.GetString("NewPostText", resourceCulture);
            }
        }
        
        internal static string SkipChildConfirmationMessage {
            get {
                return ResourceManager.GetString("SkipChildConfirmationMessage", resourceCulture);
            }
        }
        
        internal static string GetAddEditAgendaPostApi {
            get {
                return ResourceManager.GetString("GetAddEditAgendaPostApi", resourceCulture);
            }
        }
        
        internal static string EditAgendaText {
            get {
                return ResourceManager.GetString("EditAgendaText", resourceCulture);
            }
        }
        
        internal static string GetClassesForAgendaApi {
            get {
                return ResourceManager.GetString("GetClassesForAgendaApi", resourceCulture);
            }
        }
        
        internal static string GetClassStudentsApi {
            get {
                return ResourceManager.GetString("GetClassStudentsApi", resourceCulture);
            }
        }
        
        internal static string DeleteSubmissionWarningText {
            get {
                return ResourceManager.GetString("DeleteSubmissionWarningText", resourceCulture);
            }
        }
        
        internal static string GetCalendarAgendaAttachmentFilesApi {
            get {
                return ResourceManager.GetString("GetCalendarAgendaAttachmentFilesApi", resourceCulture);
            }
        }
        
        internal static string AttachmentAlreadyAddedText {
            get {
                return ResourceManager.GetString("AttachmentAlreadyAddedText", resourceCulture);
            }
        }
        
        internal static string SaveAgendaPostDataApi {
            get {
                return ResourceManager.GetString("SaveAgendaPostDataApi", resourceCulture);
            }
        }
        
        internal static string OnlineLessonApiUrl {
            get {
                return ResourceManager.GetString("OnlineLessonApiUrl", resourceCulture);
            }
        }
        
        internal static string OnlineLessonPageTitle {
            get {
                return ResourceManager.GetString("OnlineLessonPageTitle", resourceCulture);
            }
        }
        
        internal static string TopupText {
            get {
                return ResourceManager.GetString("TopupText", resourceCulture);
            }
        }
        
        internal static string SubmissionsText {
            get {
                return ResourceManager.GetString("SubmissionsText", resourceCulture);
            }
        }
        
        internal static string DashboardText {
            get {
                return ResourceManager.GetString("DashboardText", resourceCulture);
            }
        }
        
        internal static string TopupHistoryApiUrl {
            get {
                return ResourceManager.GetString("TopupHistoryApiUrl", resourceCulture);
            }
        }
        
        internal static string TopupHistoryPageTitle {
            get {
                return ResourceManager.GetString("TopupHistoryPageTitle", resourceCulture);
            }
        }
        
        internal static string AmountEmptyErrorMessage {
            get {
                return ResourceManager.GetString("AmountEmptyErrorMessage", resourceCulture);
            }
        }
        
        internal static string EnterReasonEmptyErrorMessage {
            get {
                return ResourceManager.GetString("EnterReasonEmptyErrorMessage", resourceCulture);
            }
        }
        
        internal static string GetPaymentSettingsUrl {
            get {
                return ResourceManager.GetString("GetPaymentSettingsUrl", resourceCulture);
            }
        }
        
        internal static string SubmissionErrorTitle {
            get {
                return ResourceManager.GetString("SubmissionErrorTitle", resourceCulture);
            }
        }
        
        internal static string SubmissionErrorMessage {
            get {
                return ResourceManager.GetString("SubmissionErrorMessage", resourceCulture);
            }
        }
        
        internal static string SubmissionApiUrl {
            get {
                return ResourceManager.GetString("SubmissionApiUrl", resourceCulture);
            }
        }
        
        internal static string SubmissionSaveTitle {
            get {
                return ResourceManager.GetString("SubmissionSaveTitle", resourceCulture);
            }
        }
        
        internal static string SubmissionSaveMessage {
            get {
                return ResourceManager.GetString("SubmissionSaveMessage", resourceCulture);
            }
        }
        
        internal static string GetSubmittedChequeListUrl {
            get {
                return ResourceManager.GetString("GetSubmittedChequeListUrl", resourceCulture);
            }
        }
        
        internal static string WeekendDateError {
            get {
                return ResourceManager.GetString("WeekendDateError", resourceCulture);
            }
        }
        
        internal static string SameWeekError {
            get {
                return ResourceManager.GetString("SameWeekError", resourceCulture);
            }
        }
        
        internal static string AssignmentLabel {
            get {
                return ResourceManager.GetString("AssignmentLabel", resourceCulture);
            }
        }
        
        internal static string LearningOutcomeLabel {
            get {
                return ResourceManager.GetString("LearningOutcomeLabel", resourceCulture);
            }
        }
        
        internal static string PdcReplacementText {
            get {
                return ResourceManager.GetString("PdcReplacementText", resourceCulture);
            }
        }
        
        internal static string GetCertificateDataUrl {
            get {
                return ResourceManager.GetString("GetCertificateDataUrl", resourceCulture);
            }
        }
        
        internal static string BirthdayPopupTitle {
            get {
                return ResourceManager.GetString("BirthdayPopupTitle", resourceCulture);
            }
        }
        
        internal static string GetMiscellaneousPaymentUrl {
            get {
                return ResourceManager.GetString("GetMiscellaneousPaymentUrl", resourceCulture);
            }
        }
        
        internal static string ResourceSaveSuccessMessage {
            get {
                return ResourceManager.GetString("ResourceSaveSuccessMessage", resourceCulture);
            }
        }
        
        internal static string GetGetLibraryDataUrl {
            get {
                return ResourceManager.GetString("GetGetLibraryDataUrl", resourceCulture);
            }
        }
        
        internal static string GetTeacherFeedbackDataUrl {
            get {
                return ResourceManager.GetString("GetTeacherFeedbackDataUrl", resourceCulture);
            }
        }
        
        internal static string UpdateTeacherFeedbackDataUrl {
            get {
                return ResourceManager.GetString("UpdateTeacherFeedbackDataUrl", resourceCulture);
            }
        }
        
        internal static string CertificateNotAvailableMessage {
            get {
                return ResourceManager.GetString("CertificateNotAvailableMessage", resourceCulture);
            }
        }
        
        internal static string CacheValidityPeriodInMins {
            get {
                return ResourceManager.GetString("CacheValidityPeriodInMins", resourceCulture);
            }
        }
        
        internal static string CancelAgendaText {
            get {
                return ResourceManager.GetString("CancelAgendaText", resourceCulture);
            }
        }
        
        internal static string DeleteAgendaApiUrl {
            get {
                return ResourceManager.GetString("DeleteAgendaApiUrl", resourceCulture);
            }
        }
        
        internal static string UpdateFamilyDetailsTitle {
            get {
                return ResourceManager.GetString("UpdateFamilyDetailsTitle", resourceCulture);
            }
        }
        
        internal static string InsertNewsLog {
            get {
                return ResourceManager.GetString("InsertNewsLog", resourceCulture);
            }
        }
        
        internal static string DailyLimitText {
            get {
                return ResourceManager.GetString("DailyLimitText", resourceCulture);
            }
        }
        
        internal static string SaveDailyLimitApiUrl {
            get {
                return ResourceManager.GetString("SaveDailyLimitApiUrl", resourceCulture);
            }
        }
        
        internal static string DailyLimitSaveSuccessMessage {
            get {
                return ResourceManager.GetString("DailyLimitSaveSuccessMessage", resourceCulture);
            }
        }
        
        internal static string GetClassesForWeeklyPlanApi {
            get {
                return ResourceManager.GetString("GetClassesForWeeklyPlanApi", resourceCulture);
            }
        }
        
        internal static string SaveAgendaQuickPostDataApi {
            get {
                return ResourceManager.GetString("SaveAgendaQuickPostDataApi", resourceCulture);
            }
        }
        
        internal static string AddNewAgendaQuickPostDataApi {
            get {
                return ResourceManager.GetString("AddNewAgendaQuickPostDataApi", resourceCulture);
            }
        }
        
        internal static string LoadAgendaWeeklyPostFormApi {
            get {
                return ResourceManager.GetString("LoadAgendaWeeklyPostFormApi", resourceCulture);
            }
        }
        
        internal static string GetAgendaWeeklyPlanDataApi {
            get {
                return ResourceManager.GetString("GetAgendaWeeklyPlanDataApi", resourceCulture);
            }
        }
        
        internal static string UploadAgendaQuickPostAttachmentFilesApi {
            get {
                return ResourceManager.GetString("UploadAgendaQuickPostAttachmentFilesApi", resourceCulture);
            }
        }
        
        internal static string LoadAgendaWeeklyPostPageInEditModeApi {
            get {
                return ResourceManager.GetString("LoadAgendaWeeklyPostPageInEditModeApi", resourceCulture);
            }
        }
        
        internal static string GetAgendaWeeklyGroupDataApi {
            get {
                return ResourceManager.GetString("GetAgendaWeeklyGroupDataApi", resourceCulture);
            }
        }
        
        internal static string DeleteAgendaWeeklyPlanApi {
            get {
                return ResourceManager.GetString("DeleteAgendaWeeklyPlanApi", resourceCulture);
            }
        }
        
        internal static string ChangePasswordApi {
            get {
                return ResourceManager.GetString("ChangePasswordApi", resourceCulture);
            }
        }
        
        internal static string ChangePasswordNotAllowMsg {
            get {
                return ResourceManager.GetString("ChangePasswordNotAllowMsg", resourceCulture);
            }
        }
        
        internal static string ChangePasswordSaveApi {
            get {
                return ResourceManager.GetString("ChangePasswordSaveApi", resourceCulture);
            }
        }
        
        internal static string GetRegistrationPageDataApi {
            get {
                return ResourceManager.GetString("GetRegistrationPageDataApi", resourceCulture);
            }
        }
        
        internal static string RequestForReregistrationApi {
            get {
                return ResourceManager.GetString("RequestForReregistrationApi", resourceCulture);
            }
        }
        
        internal static string SaveExisitingStudentsReRegistrationApi {
            get {
                return ResourceManager.GetString("SaveExisitingStudentsReRegistrationApi", resourceCulture);
            }
        }
        
        internal static string GetProfilePhotoViewApi {
            get {
                return ResourceManager.GetString("GetProfilePhotoViewApi", resourceCulture);
            }
        }
        
        internal static string UploadStudentImageApi {
            get {
                return ResourceManager.GetString("UploadStudentImageApi", resourceCulture);
            }
        }
        
        internal static string CancelRegistrationText {
            get {
                return ResourceManager.GetString("CancelRegistrationText", resourceCulture);
            }
        }
        
        internal static string RegistrationSaveMessage {
            get {
                return ResourceManager.GetString("RegistrationSaveMessage", resourceCulture);
            }
        }
        
        internal static string GetRegistrationFormFamilyDetailsApi {
            get {
                return ResourceManager.GetString("GetRegistrationFormFamilyDetailsApi", resourceCulture);
            }
        }
        
        internal static string SaveRegistrationFormFamilyDetailsApi {
            get {
                return ResourceManager.GetString("SaveRegistrationFormFamilyDetailsApi", resourceCulture);
            }
        }
        
        internal static string SaveRegistrationFamilyAttachmentDataApi {
            get {
                return ResourceManager.GetString("SaveRegistrationFamilyAttachmentDataApi", resourceCulture);
            }
        }
        
        internal static string UploadRegistrationFamilyAttachmentFileApi {
            get {
                return ResourceManager.GetString("UploadRegistrationFamilyAttachmentFileApi", resourceCulture);
            }
        }
        
        internal static string GetRegistrationAvailableTimesApi {
            get {
                return ResourceManager.GetString("GetRegistrationAvailableTimesApi", resourceCulture);
            }
        }
        
        internal static string RegistrationAppointmentConfirmationMessage {
            get {
                return ResourceManager.GetString("RegistrationAppointmentConfirmationMessage", resourceCulture);
            }
        }
        
        internal static string BookStudentRegistrationAppointmentApi {
            get {
                return ResourceManager.GetString("BookStudentRegistrationAppointmentApi", resourceCulture);
            }
        }
        
        internal static string RegistrationAppointmentCancelMessage {
            get {
                return ResourceManager.GetString("RegistrationAppointmentCancelMessage", resourceCulture);
            }
        }
        
        internal static string GetRegistrationFormStudentDetailsApi {
            get {
                return ResourceManager.GetString("GetRegistrationFormStudentDetailsApi", resourceCulture);
            }
        }
        
        internal static string SaveStudentRegistrationFormDetailsApi {
            get {
                return ResourceManager.GetString("SaveStudentRegistrationFormDetailsApi", resourceCulture);
            }
        }
        
        internal static string DeleteRegistrationDataApi {
            get {
                return ResourceManager.GetString("DeleteRegistrationDataApi", resourceCulture);
            }
        }
        
        internal static string GetRegistrationAvailableTimesPerStudentApi {
            get {
                return ResourceManager.GetString("GetRegistrationAvailableTimesPerStudentApi", resourceCulture);
            }
        }
        
        internal static string UploadRegistrationStudentAttachmentFileApi {
            get {
                return ResourceManager.GetString("UploadRegistrationStudentAttachmentFileApi", resourceCulture);
            }
        }
        
        internal static string SaveRegistrationStudentAttachmentDataApi {
            get {
                return ResourceManager.GetString("SaveRegistrationStudentAttachmentDataApi", resourceCulture);
            }
        }
        
        internal static string GetRegistrationFormKgStudentInformationApi {
            get {
                return ResourceManager.GetString("GetRegistrationFormKgStudentInformationApi", resourceCulture);
            }
        }
        
        internal static string SaveKgStudentRegistrationFormDetailsApi {
            get {
                return ResourceManager.GetString("SaveKgStudentRegistrationFormDetailsApi", resourceCulture);
            }
        }
        
        internal static string LogRegistrationFamilyTermsAndConditionApi {
            get {
                return ResourceManager.GetString("LogRegistrationFamilyTermsAndConditionApi", resourceCulture);
            }
        }
    }
}
