-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdXbxqVvDF/wbJd+4
JW20EmPtY1RdjJwMPr2oO69yeWWgCgYIKoZIzj0DAQehRANCAATYRXKuOIF5oetU
HaSBWyiyJ7upuwb1SqhWGWEYb7nu//eySu3kzubwzcKmwJxw92kc0BPJ2dU09SLp
5Z8hk+Wj
-----END PRIVATE KEY-----